/*
 * This source file was generated by the Gradle 'init' task
 */
package ejercicios;

public class App {
    public String getGreeting() {
        return "Hola Mundo branch 1";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
